{%- set djversions = cookiecutter.django_versions.split(',') -%}
{%- set pyversions = cookiecutter.python_versions.split(',') -%}
dist: xenial
language: python

python:{% for pyver in pyversions %}
  - "{{ pyver }}"{% endfor %}

env:{% for djver in djversions %}
  - DJANGO="{{ djver }}"{% endfor %}

matrix:
  fast_finish: true{% if 'master' in cookiecutter.django_versions %}
  allow_failures:
    - env: DJANGO=master{% endif %}

install:
  - pip install tox-travis
  - pip install -r requirements/test.txt
script: tox

deploy:
  provider: pypi
  user: "{{ cookiecutter.pypi_username }}"
  on:
    tags: true
    branch: master
